const stepDefs = require('../support/step_definitions') 

When(/^I click the "(.+)" (button|checkbox|icon|input|radio button|element)$/, stepDefs.iClickTheElement)
When(/^I click the "(.+)" link in the "(.+)" section$/, stepDefs.iClickTheLinkInTheSection)
When(/^I click the "(.+)" link$/, stepDefs.iClickTheLink)
When(/^I click the "(.+)" table "(.+)" column header$/, stepDefs.iClickTheTableColumnHeader)
When(/^I click the element with selector "(.+)"$/, stepDefs.iClickTheElementWithSelector)
When(/^I complete the new order business details page$/, stepDefs.iCompleteTheNewOrderBusinessDetailsPage)
When(/^I complete the new order service details page$/, stepDefs.iCompleteTheNewOrderServiceDetailsPage)
When(/^I complete the new order service features page$/, stepDefs.iCompleteTheNewOrderServiceFeaturesPage)
When(/^I complete the new order summary page$/, stepDefs.iCompleteTheNewOrderSummaryPage)
When(/^I create an index file for any audit results$/, stepDefs.iCreateAnIndexFileForAnyAuditResults)
When(/^I ensure I am logged out$/, stepDefs.iEnsureIAmLoggedOut)
When(/^I fill in the "(.+)" input with the recorded "(.+)"$/, stepDefs.iFillInTheInputWithTheRecorded)
When(/^I fill in the "(.+)" input with the text "(.*)"$/, stepDefs.iFillInTheInputWithTheText)
When(/^I fill in the element with selector "(.+)" with the text "(.*)"$/, stepDefs.iFillInTheElementWithTheSelectorWithTheText)
When(/^I go to the "(.+)" page(| \(mocking TIL calls\))$/, stepDefs.iGoToThePage)
When(/^I go to the url "(.+)"(| \(mocking TIL calls\))$/, stepDefs.iGoToTheUrl)
When(/^I log in as a partner$/, stepDefs.iLogInAsAPartner)
When(/^I navigate from the dashboard to the "(.+)" page$/, stepDefs.iNavigateFromTheDashboardToThePage)
When(/^I record the "(.+)" as the "(.+)"$/, stepDefs.iRecordTheAsThe)
When(/^I record the "(.+)" input as the "(.+)"$/, stepDefs.iRecordTheInputAsThe)
When(/^I record the text "(.+)" as the "(.+)"$/, stepDefs.iRecordTheTextAsThe)
When(/^I select the "(.+)" option in the "(.+)" dropdown list$/, stepDefs.iSelectTheOptionInTheDropdownList)
When(/^I select the recorded "(.+)" option in the "(.+)" dropdown list$/, stepDefs.iSelectTheRecordedOptionInTheDropdownList)
When(/^I set the "(.+)" range to "(.+)"$/, stepDefs.iSetTheRangeTo)
When(/^I take a screenshot named "(.+)"$/, stepDefs.iTakeAScreenshot)
When(/^I wait for (\d+.?\d*) minutes?$/, stepDefs.iWaitForMinutes)
When(/^I wait for (\d+.?\d*) seconds?$/, stepDefs.iWaitForSeconds)


Then(/^I should(| still)(| not) be on the "(.+)" page$/, stepDefs.iShouldBeOnThePage)
Then(/^I should(| still)(| not) be on the url "(.+)"$/, stepDefs.iShouldBeOnTheUrl)
Then(/^I should(| still)(| not) see the "(.+)" (button|dropdown list|icon|input|link|radio button|section|table)$/, stepDefs.iShouldSeeTheElement)
Then(/^I should(| not) see the recorded "(.+)"(| in the "(.+)" section)$/, stepDefs.iShouldSeeTheRecordedInTheSection)
Then(/^I should(| not) see the text "(.+)"(| in the "(.+)" section)$/, stepDefs.iShouldSeeTheTextInTheSection)
Then(/^I should see the text of "(.+)" in the "(.+)" segment$/, stepDefs.iShouldSeeTheTextInTheSegment)
Then(/^the "(.+)" (checkbox|radio button) should(| not) be (checked|selected)$/, stepDefs.theCheckboxOrRadioButtonShouldBeChecked)
Then(/^the file "(.+)" should(| not) exist$/, stepDefs.theFileShouldExist)
Then(/^the "(.+)" input should(| not) contain the recorded "(.+)"$/, stepDefs.theInputShouldContainTheRecorded)
Then(/^the "(.+)" input should(| not) contain the text "(.*)"$/, stepDefs.theInputShouldContainTheText)
Then(/^the "(.+)" dropdown list should(| not) have the recorded value "(.+)"$/, stepDefs.theDropdownListShouldHaveTheRecordedValue)
Then(/^the "(.+)" dropdown list should(| not) have the value "(.*)"$/, stepDefs.theDropdownListShouldHaveTheValue)
Then(/^the "(.+)" table should(| not) be ordered by the "(.+)" column (ascending|descending)$/, stepDefs.theTableShouldBeOrderedByTheColumn)
Then(/^the "(.+)" table should(| not) contain the recorded "(.+)"$/, stepDefs.theTableShouldContainTheRecorded)
Then(/^the "(.+)" table should(| not) contain the text "(.*)"$/, stepDefs.theTableShouldContainTheText)
Then(/^the "(.+)" table should(| not) have (.+) visible rows?$/, stepDefs.theTableShouldHaveRows)
Then(/^the "(.+)" table should(| not) have a total of (.+) rows?$/, stepDefs.theTableShouldHaveATotalOfRows)
Then(/^I should(| not) see the text "(.+)" in the "(.+)" field at create order summary page$/,stepDefs.iShouldSeeTheTextInTheCreateOrderSummaryPage)
Then(/^I wait for the element "(.+)"$/, stepDefs.iWaitForElement)
Then(/^I wait for "(.+)" text$/, stepDefs.iWaitForText)
Then(/^I wait for page to load$/,stepDefs.iWaitForPagetoLoad)